"""create sources table

Revision ID: 157831e5ab5b
Revises: 0ca6b90bca26
Create Date: 2026-09-01 05:20:49.537949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157831e5ab5b'
down_revision = '0ca6b90bca26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('RESTAURANT_WEBSITE', 'THIRD_PARTY_MENU_PROVIDER', 'PDF_MENU', 'MANUAL_ENTRY', name='source_type'), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('is_verified_domain', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_restaurant_id'), 'sources', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_restaurant_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
