"""create restaurant menu dish and proposed_change tables

Revision ID: 2186b16aec20
Revises: 676658c5c999
Create Date: 2026-09-01 06:58:42.628951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2186b16aec20'
down_revision = '676658c5c999'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposed_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('RESTAURANT', 'RESTAURANT_LOCATION', 'MENU', 'MENU_CATEGORY', 'DISH', name='proposed_change_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('structured_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', name='proposed_change_status'), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_changes_agent_run_id'), 'proposed_changes', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_proposed_changes_entity_id'), 'proposed_changes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_proposed_changes_status'), 'proposed_changes', ['status'], unique=False)
    op.create_index(op.f('ix_proposed_changes_thread_id'), 'proposed_changes', ['thread_id'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('logo_url', sa.String(length=2048), nullable=True),
    sa.Column('cover_image_url', sa.String(length=2048), nullable=True),
    sa.Column('gallery_image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('cuisine_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposed_change_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PUBLISHED', name='proposed_change_status'), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposed_change_id'], ['proposed_changes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_proposed_change_id'), 'approvals', ['proposed_change_id'], unique=False)
    op.create_table('menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_restaurant_id'), 'menus', ['restaurant_id'], unique=False)
    op.create_table('restaurant_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_locations_restaurant_id'), 'restaurant_locations', ['restaurant_id'], unique=False)
    op.create_table('menu_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['menu_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_categories_menu_id'), 'menu_categories', ['menu_id'], unique=False)
    op.create_index(op.f('ix_menu_categories_parent_id'), 'menu_categories', ['parent_id'], unique=False)
    op.create_table('dishes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('nutrition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergens', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('review_state', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='dish_review_state'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dishes_category_id'), 'dishes', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dishes_category_id'), table_name='dishes')
    op.drop_table('dishes')
    op.drop_index(op.f('ix_menu_categories_parent_id'), table_name='menu_categories')
    op.drop_index(op.f('ix_menu_categories_menu_id'), table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_index(op.f('ix_restaurant_locations_restaurant_id'), table_name='restaurant_locations')
    op.drop_table('restaurant_locations')
    op.drop_index(op.f('ix_menus_restaurant_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_approvals_proposed_change_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_proposed_changes_thread_id'), table_name='proposed_changes')
    op.drop_index(op.f('ix_proposed_changes_status'), table_name='proposed_changes')
    op.drop_index(op.f('ix_proposed_changes_entity_id'), table_name='proposed_changes')
    op.drop_index(op.f('ix_proposed_changes_agent_run_id'), table_name='proposed_changes')
    op.drop_table('proposed_changes')
    # ### end Alembic commands ###
