"""create source_snapshots table

Revision ID: 2e8de6675983
Revises: 2186b16aec20
Create Date: 2026-09-01 08:00:26.905657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e8de6675983'
down_revision = '2186b16aec20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('HTML', 'PDF', 'SCREENSHOT', name='snapshot_content_type'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=2048), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_length_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_content_hash'), 'source_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_snapshots_source_id'), 'source_snapshots', ['source_id'], unique=False)
    # Note: checkpoints/checkpoint_migrations/checkpoint_blobs/checkpoint_writes
    # are intentionally NOT managed here — they're created/migrated by
    # langgraph-checkpoint-postgres's AsyncPostgresSaver.setup() (see
    # infrastructure/checkpointer.py), not Alembic. Autogenerate flags them
    # as "removed" because they're invisible to SQLAlchemy's metadata; that
    # diff was discarded when reviewing this migration, per this repo's
    # "always review autogenerated migrations before applying" convention
    # (see database/README.md).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_snapshots_source_id'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_content_hash'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    # ### end Alembic commands ###
