"""create agent_runs table

Revision ID: 676658c5c999
Revises: 157831e5ab5b
Create Date: 2026-09-01 05:52:30.903639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676658c5c999'
down_revision = '157831e5ab5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_type', sa.Enum('COLLECTOR', 'REVIEWER', name='agent_workflow_type'), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='agent_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_restaurant_id'), 'agent_runs', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_workflow_type'), 'agent_runs', ['workflow_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_workflow_type'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_restaurant_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
